#!/bin/bash
set -e

source $(dirname $0)/version
cd $(dirname $0)/..

set -x

mkdir -p ${DOWNLOADS}/kernel ${DOWNLOADS}/firmware

# kernel
mkdir -p /source/build/ && cd /source/build/
git clone --depth 1 https://git.launchpad.net/~ubuntu-kernel/ubuntu/+source/linux/+git/noble/ kernel -b Ubuntu-6.8.0-31.31

# patches
if [ -n "${NOPATCHES}" ]; then
    exit 0
fi
PATCHES_DIR=/source/patches
pushd kernel
for p in `find ${PATCHES_DIR} -name "*.patch"`; do
    echo "applying $p"
    patch -p1 -i $p
done
popd
